import type { ArtifactPackage, GameSpec } from "./schemas";
import type { GamePack } from "./game-packs";
import { buildPersonaVoicePrompt } from "@/voice-profiles";

function safeId(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "generated";
}

export function buildArtifactPackageFromGameSpec(gameSpec: GameSpec, pack: GamePack): ArtifactPackage {
  const supportRoles = gameSpec.rolesOrActors.slice(0, 12);
  const cards: ArtifactPackage["cards"] = supportRoles.map((actor) => ({
    id: `card_${safeId(actor.id)}`,
    name: actor.name,
    roleOrActorId: actor.id,
    frontText: actor.publicDescription,
    privateReminder: actor.privateGoal,
    assetId: `asset_card_${safeId(actor.id)}`
  }));

  const personaCount = gameSpec.mechanics.includes("ai_personas") ? Math.max(1, Math.min(gameSpec.players.ai, 6)) : 0;
  const personas: ArtifactPackage["personas"] = personaCount > 0
    ? Array.from({ length: personaCount }, (_, index) => {
        const role = supportRoles[index % Math.max(supportRoles.length, 1)];
        const roleName = role?.name ?? "guide de partie";

        return {
          id: `ai_persona_${index + 1}`,
          displayName: `IA ${index + 1} · ${roleName}`,
          speechStyle: `immersif, concis, adapté au thème ${gameSpec.theme}`,
          publicBackstory: `Une présence IA de support pour ${gameSpec.title}, inspirée par ${roleName}.`,
          behaviorRules: [
            "Reste dans le personnage et dans le ton de la partie.",
            "N'utilise que les informations publiques sauf si le rôle secret l'autorise.",
            "Aide les joueurs humains à garder un rythme fluide sans résoudre le jeu à leur place."
          ],
          sampleLines: [
            "Je vais observer avant d'accuser.",
            "Quelque chose ne colle pas dans cette histoire."
          ]
        };
      })
    : [];

  const assetPrompts: ArtifactPackage["assetPrompts"] = [
    {
      id: "hero_visual",
      kind: "hero" as const,
      prompt: `Polished board game key art for ${gameSpec.title}, ${gameSpec.theme}, ${pack.label}, safe non-graphic style.`,
      usage: "hero preview",
      safetyNotes: ["No gore", "No explicit violence"]
    },
    {
      id: "tabletop_board_visual",
      kind: "scene" as const,
      prompt: `Top-down tabletop support board for ${gameSpec.title}, ${gameSpec.theme}, visible phase track, role deck zones, premium board game layout, no text, safe non-graphic style.`,
      usage: "play support board",
      safetyNotes: ["No gore", "No explicit violence", "No readable text in image"]
    },
    ...supportRoles.map((actor) => ({
      id: `asset_card_${safeId(actor.id)}`,
      kind: "card" as const,
      prompt: `Role card illustration for ${actor.name} in ${gameSpec.title}, ${gameSpec.theme}, ${actor.teamOrSide} faction, ornate tabletop card frame, no text, safe non-graphic style.`,
      usage: `card for ${actor.name}`,
      safetyNotes: ["Stylized only"]
    })),
    ...personas.map((persona) => ({
      id: `voice_${safeId(persona.id)}`,
      kind: "voice" as const,
      prompt: buildPersonaVoicePrompt(persona, gameSpec.theme, undefined),
      usage: `Gradium voice/persona direction for ${persona.displayName}`,
      safetyNotes: ["No impersonation of real living people", "Keep voice assistant safe and fictional"]
    }))
  ];

  return {
    rulesMarkdown: `# ${gameSpec.title}\n\n${gameSpec.pitch}\n\n## Core loop\n${gameSpec.coreLoop.map((step) => `- ${step}`).join("\n")}\n\n## Win conditions\n${gameSpec.winConditions.map((condition) => `- ${condition}`).join("\n")}`,
    cards,
    personas,
    assetPrompts,
    codeStubs: [
      {
        path: `src/generated/${safeId(gameSpec.gameId)}/config.ts`,
        purpose: "Generated game package configuration.",
        content: `export const generatedGame = ${JSON.stringify(
          {
            gameId: gameSpec.gameId,
            family: gameSpec.family,
            pack: gameSpec.pack,
            phases: gameSpec.phases.map((phase) => phase.id),
            mechanics: gameSpec.mechanics
          },
          null,
          2
        )};`
      }
    ],
    acceptanceTests: [
      ...pack.validationRules,
      "GameSpec contains at least one phase and one win condition.",
      "Generated visual assets are prompts only and do not affect game rules.",
      "Generated voice prompts map every AI persona to a fictional speech direction."
    ],
    validationReport: {
      status: "pass_with_notes",
      checks: [
        `Routed to ${pack.id}.`,
        "GameSpec generated by the selected LLM provider.",
        "Artifacts generated deterministically from the validated GameSpec.",
        "Voice prompts stay data-only; Gradium credentials remain server-side."
      ],
      warnings: ["Fast provider mode generates artifacts server-side to reduce model latency."],
      assumptions: gameSpec.assumptions
    }
  };
}
